export const ARTICLE_REQUEST = 'ARTICLE_REQUEST';
export const ARTICLE_SUCCESS = 'ARTICLE_SUCCESS';
export const ARTICLE_FAIL = 'ARTICLE_FAIL';

export const ARTICLE_BY_ID_REQUEST = 'ARTICLE_BY_ID_REQUEST';
export const ARTICLE_BY_ID_SUCCESS = 'ARTICLE_BY_ID_SUCCESS';
export const ARTICLE_BY_ID_FAIL = 'ARTICLE_BY_ID_FAIL';
