export const GET_PROFILES_REQUEST = 'GET_PROFILES_REQUEST';
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_PROFILES_FAIL = 'GET_PROFILES_FAIL';

export const GET_SINGLE_PROFILE_REQUEST = 'GET_SINGLE_PROFILES_REQUEST';
export const GET_SINGLE_PROFILE_SUCCESS = 'GET_SINGLE_PROFILES_SUCCESS';
export const GET_SINGLE_PROFILE_FAIL = 'GET_SINGLE_PROFILES_FAIL';
