export const RECIPE_REQUEST = 'RECIPE_REQUEST';
export const RECIPE_SUCCESS = 'RECIPE_SUCCESS';
export const RECIPE_FAIL = 'RECIPE_FAIL';

export const RECIPE_BY_ID_REQUEST = 'RECIPE_BY_ID_REQUEST';
export const RECIPE_BY_ID_SUCCESS = 'RECIPE_BY_ID_SUCCESS';
export const RECIPE_BY_ID_FAIL = 'RECIPE_BY_ID_FAIL';
